### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by guoeq** [HeJingWei/HookAlipay#2]
2020-05-13 23:25:10.970 23265-23265/com.hooker.hookalipay W/System.err: java.lang.reflect.InvocationTargetException
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at mirror.RefStaticMethod.call(RefStaticMethod.java:119)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.env.SpecialComponentList.<clinit>(SpecialComponentList.java:77)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:322)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:218)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:213)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:149)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.os.Looper.loop(Looper.java:201)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6820)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Application.getPackageManager()' on a null object reference
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.webkit.WebViewFactory.isWebViewSupported(WebViewFactory.java:111)
2020-05-13 23:25:10.973 23265-23265/com.hooker.hookalipay W/System.err:     at android.webkit.WebViewFactory.getUpdateService(WebViewFactory.java:513)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err: 	... 17 more
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err: java.lang.NullPointerException: null receiver
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.env.SpecialComponentList.<clinit>(SpecialComponentList.java:77)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:322)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:218)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:213)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:149)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.os.Looper.loop(Looper.java:201)
2020-05-13 23:25:10.974 23265-23265/com.hooker.hookalipay W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6820)
2020-05-13 23:25:10.975 23265-23265/com.hooker.hookalipay W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-13 23:25:10.975 23265-23265/com.hooker.hookalipay W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
2020-05-13 23:25:10.975 23265-23265/com.hooker.hookalipay W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

**Comment by ZJLeBron** [comment]
这代码里啥也没有啊。。。
